### ISSUE TITLE
Make smaragdant crystal block with 4 smaragdant crystal shard [Suggestion] 

### ISSUE THREAD

**Issue by ChristopherJ123** [quiqueck/BetterEnd#106]
### Description

Make smaragdant crystal block with 4 smaragdant crystal shard or 9 shards. This is similar with how you craft amethyst block with 4 amethyst shard.

**Comment by quiqueck** [comment]
As far as I can see, you already changed the Recipe, right?

**Comment by Necrontyrr** [comment]
Yes, I added [a new recipe](https://github.com/quiqueck/BetterEnd/blob/0ef3b7e11ec5f60653b13b5e1789188ea5c11f12/src/main/java/org/betterx/betterend/recipe/CraftingRecipes.java#L493) :)

**Comment by quiqueck** [comment]
Nice, and thanks again for the PR :)
