### ISSUE TITLE
[Bug] Ender dragon can break pillar blocks

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterEnd#11]
### What happened?

In old versions of BN all stones, metals and their blocks were immune to dragon, in new (1.18.2 and 1.19) - not
![2022-06-16_21 48 54](https://user-images.githubusercontent.com/17707380/174143891-87a98fbb-8581-405b-a996-c2f4da5eff7d.png)

### BetterEnd

2.0.2

### BCLib

2.0.5

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
None
```

### Other Mods

```shell
better-nether-7.0.2
iris-mc1.19-1.2.5
sodium-fabric-mc1.19-0.4.2+build.16
```

**Comment by quiqueck** [comment]
Sound be fixed in the just release 2.0.3 Version
