### ISSUE TITLE
cant open the end for dummies book

### ISSUE THREAD

**Issue by Kacperrrrrrr** [quiqueck/BetterEnd#114]
like in the title. i dont know what could be issue here. i have installed patchloui but it is still not working

**Comment by Isaacbg** [comment]
have you been able to solve it? same is happening to me

**Comment by Garwinium** [comment]
i also have this issue

**Comment by Palibrix** [comment]
Also have this issue on 1.18.2 fabric for a few months

**Comment by Palibrix** [comment]
Using betterend 1.1.1, bclib 1.4.7, fabric api 0.58.0

**Comment by quiqueck** [comment]
Did you install patchouli? You need it for the book.

**Comment by Garwinium** [comment]
Yes I have it installed, Kac (OP) also said they have it installed

**Comment by quiqueck** [comment]
Are you all on 1.18.2?

**Comment by Garwinium** [comment]
Yes i am using 1.18.2

**Comment by Palibrix** [comment]
Yes, I'm using Patchouli 71.1. I can open book via "open-patchouli-book" command, but not with book item. But I checked patchouli files on git and they are quite empty (only ritual entry contains info, all categories are empty), so I don't think that's a huge loss

**Comment by Pultex** [comment]
> Yes, I'm using Patchouli 71.1. I can open book via "open-patchouli-book" command, but not with book item. But I checked patchouli files on git and they are quite empty (only ritual entry contains info, all categories are empty), so I don't think that's a huge loss

true nothing in there just two entries

**Comment by TheWyzer** [comment]
I am having the same issue as well, book will not open at all.
BetterEnd 1.1.1
BCLib 1.4.7
Fabric API 0.67.0
Fabric Loader 0.14.11
Minecraft 1.18.2
Patchouli 71.1
