### ISSUE TITLE
Question: How can I add your infusion recipes through datapacks?

### ISSUE THREAD

**Issue by notIkibo** [quiqueck/BetterEnd#115]
Hey there,

I would like to add more enchanted book recipes myself (also enchantments of other mods) and would like to have the formula on how it is structured. The recipes itself have a .class (which I don't know anything about) and so I couldn't really see into it with Notepad++

So how do I add infusion recipes through a datapack? And should it also be a class data type instead of json?

I'm just working on a server for my friends and want to make it more or less chill when it comes to enchantments late-game-y and cross compatibility.

Thanks so much.

Ikibo

**Comment by quiqueck** [comment]
Have a look at #78. There is a datapack created by [lxly9](https://github.com/lxly9) that includes Infusion recipes.
