### ISSUE TITLE
cant get it to work with the mods i want on curseforge. 

### ISSUE THREAD

**Issue by SnowyHusky** [quiqueck/BetterEnd#116]
i having a problem with getting the better end and better nether to work with a file on curseforge. i  have a few other mods in the folder so i dont know if there is a problem with them interacting together the file is in the latest version for curseforge and the file of both the better end and the better nether are the lates as well. Curseforge is 43.1.52 and the files im trying to download are [better-end-2.1.1 [1.19.2] [better-nether-7.1.1 [1.19.2]. 

the mods i have installed are YungsExtras-1.19.2-Forge-3.1.0. YungsApi-1.19.2-Forge-3.8.2 waystones-forge-1.19-11.1.0 veinmining-forge-1.0.0-beta.5+1.19.2 sophisticatedcore-1.19.2-0.5.15.142  sophisticatedbackpacks-1.19.2-3.18.29.719 TerraBlender-forge-1.19.2-2.0.1.128 easy_villagers-1.19.2-1.0.0 CraftTweaker-forge-1.19.2-10.0.16 BiomesOPlenty-1.19.2-17.1.1.162 betteranimalsplus-1.19-11.0.7-forge YungsBridges-1.19.2-Forge-3.1.0 balm-4.5.3 architectury-6.3.49-forge  

im new to mods for minecraft so i dont know exactly how to work with them its not the same or even close to that of the sims. some help would be greatly appreciated

**Comment by quiqueck** [comment]
Hi, and thanks for contacting me.

BetterEnd and BetterNether are a Fabric Mods, you can not combine it with forge mods.
