### ISSUE TITLE
[Suggestion] Compress sounds to reduce file size of mod

### ISSUE THREAD

**Issue by purejosh** [quiqueck/BetterEnd#117]
### Description

With your permission, I would like to compress the sounds included in BetterEnd and provide them to you, so you can reduce the overall size of the mod. 

I was able to reduce one of the sounds up to 1/4th its original size, and that was with a basic mixdown. Minecraft plays sounds in mono. Having a stereo track makes no sense, and consumes space. With a basic compression and mono mixdown, I could turn this mod from 84MB to 30MB. Possibly even further.

**Comment by quiqueck** [comment]
I think #2 will solve this issue.

**Comment by quiqueck** [comment]
Oh, and if you already did some compression, please feel free to generate a PR (or send me the files). If there is a reduction, I will add those as well.

**Comment by purejosh** [comment]
I'll review the files to see if my methods were more effective.

**Comment by quiqueck** [comment]
Great, thank you very much :)

**Comment by purejosh** [comment]
I'm able to reduce the file sizes down to roughly 33% of its original size. This is only applying to audio. And note, I'm not simply running these through a compressor, I'm actually engineering them. 

1. I mixed down to mono (Minecraft only plays in mono, anyway) 
2. I reduced the rate (HZ) of the project to 50% of its original rate (It reduces the EXTREMELY high treble range, while almost cutting the size in half)

With these two changes, I've been getting a reduction rate of 1/3rd the original size. I've listened to the audios, and the only difference I can hear is the stereo to mono changes. 

Here's a couple sample files, please give them a listen and let me know if you want me to process the remainder of the files as well. 

[sounds.zip](https://github.com/quiqueck/BetterEnd/files/10200596/sounds.zip)

**Comment by quiqueck** [comment]
Thanks for the sample. I think in the beginning of the venkatesananda track, the acoustic guitar isn't as clear. It feel like the typical compression vibrato/whawha...

**Comment by purejosh** [comment]
Quick question, are these tracks meant for discs, or are they ambient/music tracks? 

I'm curious because if it's a disc, it should be in mono. And if it's an ambient/music track (plays as background music would), it should be stereo. 

https://bugs.mojang.com/browse/MC-146721?focusedId=552022&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-552022

**Comment by quiqueck** [comment]
Both actually. There are some disc tracks and some for ambient
