### ISSUE TITLE
Config does not work

### ISSUE THREAD

**Issue by Mahadbaloch** [quiqueck/BetterEnd#119]
Disabling custom sky and fog density from config file does not work. Is there any way to disable these CLIENT side features

**Comment by quiqueck** [comment]
Hm, I tested with customSky, and changing the value from true to false in `betterend/client.json` disables our custom renderer.

Fog-rendering is now controlled in `bclib/client.json` using the `rendering.customFogRendering`.

**Comment by Mahadbaloch** [comment]
After some weirdness and the config cloning itself for some reason they started working

**Comment by quiqueck** [comment]
You probably know this, but just to be safe. You need to restart Minecraft when the config is changed.
