### ISSUE TITLE
[Bug] Biome structures can be generated on water

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterEnd#12]
### What happened?

Sometimes biome structures can appear on water surfaces (lakes), probably they are missing terrain check
![2022-06-16_21 57 06](https://user-images.githubusercontent.com/17707380/174145140-fa5388ef-2383-463c-a76c-df081151dd1d.png)
![2022-06-16_21 57 28](https://user-images.githubusercontent.com/17707380/174145143-87990eb5-70cf-48d1-ba82-7bfe58307fe4.png)

### BetterEnd

2.0.2

### BCLib

2.0.5

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
None
```

### Other Mods

```shell
better-nether-7.0.2
iris-mc1.19-1.2.5
sodium-fabric-mc1.19-0.4.2+build.16
```

**Comment by quiqueck** [comment]
Should be fixed in 2.0.5
