### ISSUE TITLE
[Suggestion] I want to advertise your BetterEnd mod to MCBBS.

### ISSUE THREAD

**Issue by imnotyangjiu** [quiqueck/BetterEnd#121]
### Description

Hello.I advertise your BetterNether mod to MCBBS 1 month ago.People responded very well and all downloaded mod.So today I want to advertise your BetterEnd mod to MCBBS.MCBBS is the largest Minecraft forum in China.People in MCBBS can contact me for suggestion or reporting bugs in Chinese, and then I can contact you in English.We can make this mod better and better together.Thank you!

**Comment by quiqueck** [comment]
Sure, and thanks :)
