### ISSUE TITLE
[Bug] Floating budding smaragdant crystals

### ISSUE THREAD

**Issue by Flyvee** [quiqueck/BetterEnd#123]
### What happened?

I found a newly generated lush smaragdant cave in my world to find the new budding crystals, when the first I found were generated in the center of the cave tunnel in the air.
![2022-12-02_20 48 10](https://user-images.githubusercontent.com/30793646/205367172-75eeaf56-cd0e-485c-b314-98d04cf376d2.png)

### BetterEnd

2.1.2

### BCLib

2.1.4

### Fabric API

0.67.1

### Fabric Loader

0.14.10

### Minecraft

1.19.2

**Comment by Necrontyrr** [comment]
Can you give me seed and coordinates?

**Comment by Flyvee** [comment]
The seed is -5930464648540265214 but unfortunately I've already traveled quite far from that cave but I think the reason for the floating, is that in that cave, the only other smaragdant crystals, were the non block variety as in the next cave, I found how they were meant to be:
![2022-12-02_21 29 56](https://user-images.githubusercontent.com/30793646/205371669-f8e7e44d-d4a7-4ac7-8d31-17fc4ec74f3d.png)

**Comment by Flyvee** [comment]
But it could be around -1600 -2500 or north/north west of there. This is the path I've traveled and it was near the start I found that cave: 
![end map](https://user-images.githubusercontent.com/30793646/205372440-f504f56f-9c74-416f-ab5d-e05399c1b6ea.png)

**Comment by quiqueck** [comment]
Thanks for reporting. It sounds like they are not removed by the cave carver. Probably a missing tag...

**Comment by quiqueck** [comment]
The fix was just released with the new 1.19.3 Version. It will also be included in the next update for older 1.19-Versions.
