### ISSUE TITLE
[Bug]  Mossy obsidian and mossy dragon bone blocks currently can't spread.

### ISSUE THREAD

**Issue by Flyvee** [quiqueck/BetterEnd#126]
### What happened?

The code to make the other mossy blocks spread, wasn't done for the mossy obsidian to obsidian blocks and mossy dragon bone for dragon bone blocks. 
![parent](https://user-images.githubusercontent.com/30793646/206279568-323e18f0-73ba-41d8-b143-25ec40c9524c.png)
Here in the parent branch (https://github.com/paulevsGitch/BetterEnd/tree/58a2894658c1457a50f4200b112df4c034873a1b/src/main/java/ru/betterend/registry)/EndTags.java
The mossy obsidian and mossy dragon bone is done there on line 97 and 98, but in the current branch:
![current](https://user-images.githubusercontent.com/30793646/206279909-5e8ed38d-45b7-477f-88af-4a3590da5030.png)
It is missing.

### BetterEnd

2.1.2

### BCLib

2.1.4

### Fabric API

0.67.1

### Fabric Loader

0.14.10

### Minecraft

1.19.2

**Comment by quiqueck** [comment]
Thanks for reporting. Just as a small info, this is done differently now. Bonemeal-spreading is Tag-Based now.

This code adds the tag to the block
https://github.com/quiqueck/BetterEnd/blob/1c0bf30f088ac22e71cca301e69e8fe998a70381/src/main/java/org/betterx/betterend/registry/EndBlocks.java#L138-L142

If you bonemeal a block that has the `BONEMEAL_TARGET_OBSIDIAN`-Tag, and if there is another mossy obsidian in the 3x3 Neighbourhood there is a chance that it will spread on the clicked block.
https://github.com/quiqueck/BCLib/blob/1f4f1e79e927b3546a529324034ccc07fb4ee1de/src/main/java/org/betterx/bclib/api/v3/tag/BCLBlockTags.java#L36

But maybe that is not working as it should...

**Comment by quiqueck** [comment]
Ah, but I think I did not register that pair :(

Will fix that in the next release...

**Comment by quiqueck** [comment]
Released with BCLib 2.1.5
