### ISSUE TITLE
[Bug] Boot looping with glitched unicode characters all over the loading screen

### ISSUE THREAD

**Issue by Ferynix** [quiqueck/BetterEnd#127]
### What happened?

Upon loading the game, the mojang screen fades out, showing a glitched main menu or betterx warning, along with tons of glitched box unicode characters plastered randomly around the screen, and this only flashes for a second, before it starts over, loading again, and repeating the same glitched popup.

(Video of the bug: [https://imgur.com/a/7rHc4B0](https://imgur.com/a/7rHc4B0) )

Its almost like it corrupts the loader / main menu.

### BetterEnd

3.1.1

### BCLib

2.2.3

### Fabric API

0.69.0

### Fabric Loader

0.14.11

### Minecraft

1.19.3

### Relevant log output

[https://mclo.gs/pHchGGv](https://mclo.gs/pHchGGv)

**Comment by Ferynix** [comment]
Update: I was chatting with the AE2 dev, and they told me this is a common texture path bug, and I saw a similar error while testing.

Something isnt referenced correctly

**Comment by Terrafin72** [comment]
The problem is sodium.

**Comment by Ferynix** [comment]
> The problem is sodium.

BetterNether and BCLib work fine with sodium. The error is a texture path.. So that doesnt make any sense

**Comment by Terrafin72** [comment]
I have two modpack :

-First modpack : the game have a infinite loop with sodium.
-Second modpack : dont have problem with sodium.

That weird...
