### ISSUE TITLE
Eternal Portals not spawning in the end 

### ISSUE THREAD

**Issue by PlsNoFlame** [quiqueck/BetterEnd#131]
### What happened?

In my world, there are no eternal portals spawning in the end. 

### BetterEnd

1.1.1

### BCLib

1.4.7

### Fabric Loader

0.14.9

### Minecraft

1.18.2

### Other Mods

```shell
Valhelsia: Enchanced Vanilla

https://www.curseforge.com/minecraft/modpacks/valhelsia-enhanced-vanilla
```

**Comment by AnxiousWizardry** [comment]
Hi, so this won't fix like the code, but if you can, try building the basic exit portal and the ritual to revive the dragon, and that should get a working exit portal. This worked with 1.19.2 so I think it should work with 1.18.2 as I just had to do it to reopen the end
