### ISSUE TITLE
[Bug] crystalite/armoured elytra breaking like armour rather than elytra

### ISSUE THREAD

**Issue by FoolishGold** [quiqueck/BetterEnd#136]
### What happened?

A friend's crystalite elytra broke midair and rather than being unusable but repairable (like regular elytra) simply disappeared (like regular armour.) Initially I thought this could be an issue with the other mods installed, but having tested both the crystalite and armoured elytra on singleplayer without any extra mods/datapacks, both broke like armour not elytra. 
The test involved standing on a cactus with elytra equipped until they broke as flight durability was taking too long.
I theorise that it has something to do with the game thinking that they are armour not elytra but I could well be wrong as I have zero modding/coding experience.

### BetterEnd

2.1.2

### BCLib

2.1.5

### Fabric API

0.72.0

### Fabric Loader

0.14.12

### Minecraft

1.19.2

### Relevant log output

```shell
N/A
```

### Other Mods

```shell
N/A
```

**Comment by quiqueck** [comment]
hm, I think they were actually designed that way...

**Comment by FoolishGold** [comment]
> hm, I think they were actually designed that way...

huh, tbh I thought it might've been intentional for balance or something but I'd asked about it in the discord and got told they should be working like elytra and to submit a bug report

**Comment by quiqueck** [comment]
Ah, maybe they did once work just like elytra. :) I'll check when this change was introduced.
