### ISSUE TITLE
[Suggestion] Forge Compatibility

### ISSUE THREAD

**Issue by DiscoDude96** [quiqueck/BetterEnd#14]
### Description

Add forge compatibility so more players can have this mod.

**Comment by quiqueck** [comment]
Sorry, but I am not a forge developer :)

**Comment by AgainPsychoX** [comment]
There is https://www.curseforge.com/minecraft/mc-mods/betterend-forge-port  (sources: https://github.com/Beethoven92/BetterEndForge) or related forks, i.e. https://github.com/MCTeamPotato/Better-End-Potato-Edition 


_Adding this comment for further readers._

**Comment by NinjaSam5399** [comment]
> Sorry, but I am not a forge developer :)

I can't believe you anymore. I quit this mod.
