### ISSUE TITLE
[Bug] Blue vine seeds won't grow naturally

### ISSUE THREAD

**Issue by cruxtruder** [quiqueck/BetterEnd#147]
### What happened?

A bug happened!

Apparently they lack tick growth and the only way to grow them is with bone meal.

### BetterEnd

2.1.2

### BCLib

2.1.5

### Fabric API

0.72.0

### Fabric Loader

0.14.12

### Minecraft

1.19.2

**Comment by quiqueck** [comment]
Thanks for reporting, will look into it.

**Comment by quiqueck** [comment]
Should be fixed in the latest update.
