### ISSUE TITLE
Mod Isn't Seen

### ISSUE THREAD

**Issue by mamasawrekawie** [quiqueck/BetterEnd#152]
### What happened?

So I have downloaded Better End for 1.19.2 and BClib for 1.19.2 and my Minecraft dosen't even see the mod in mods. How can I sovle that?

### BetterEnd

2.1.4

### BCLib

2.1.6

### Fabric API

0

### Fabric Loader

0

### Minecraft

1.19.2

**Comment by quiqueck** [comment]
You probably do, and I am sorry to ask, but since the version numbers are 0 for fabric I have to ask if you do run fabric? (missing fabric would be the very simple explanation)

**Comment by mamasawrekawie** [comment]
I'm using Forge version

pon., 13 lut 2023, 11:09 użytkownik Frank ***@***.***>
napisał:

**Comment by quiqueck** [comment]
Ah, ok. This is the wrong project. We only do the fabric mods. Forge ports are manage from another team. Not sure who to contact tho :(
