### ISSUE TITLE
[Bug] Using Bone Meal on an End Stone next to a Pallidium converts the End Stone into Pallidium

### ISSUE THREAD

**Issue by alerikaisattera** [quiqueck/BetterEnd#155]
### What happened?

When Bone Meal is used on an End Stone block next to a Pallidium, th End Stone block is converted into Pallidium

### BetterEnd

2.1.2

### BCLib

2.1.4

### Fabric API

0.67.0

### Fabric Loader

0.14.9

### Minecraft

1.19.2

**Comment by quiqueck** [comment]
That is actually intense behaviour similar to how nether terrain spreads.
