### ISSUE TITLE
[Bug] Server Crashes idk why

### ISSUE THREAD

**Issue by CeZerTyui** [quiqueck/BetterEnd#158]
### What happened?

Not sure why its crashing but i did disable the ancient emeralds block things because i think thats what its making it crash. I did delete Dim1 because the end didnt spawn the biomes.. here is the log from the server :
[crash-2023-02-15_21.54.15-server.txt](https://github.com/quiqueck/BetterEnd/files/10751776/crash-2023-02-15_21.54.15-server.txt)

### BetterEnd

3.1.2

### BCLib

2.2.4

### Fabric API

0.73.2

### Fabric Loader

0.14.14

### Minecraft

1.19.3

**Comment by quiqueck** [comment]
Duplicate of #205
