### ISSUE TITLE
Netherite Smithing Hammer is consumed when used in the first slot of an anvil

### ISSUE THREAD

**Issue by RiskE80T** [quiqueck/BetterEnd#17]
### What happened?

when using the smithing hammer on an anvil, if its in the first slot the entire hammer is consumed when an item is taken out of the 3rd slot, im pretty sure this is a bug as its not consumed if in the 2nd slot 

### BetterEnd

2.0.2

### BCLib

2.0.5

### Fabric API

0.56.1

### Fabric Loader

0.14.8

### Minecraft

1.19

**Comment by ChristianKilduff** [comment]
happened to me as well, I figured hammer in first slot made most sense and then it got destroyed and was confused. Took a few tries to realize the bug only applied to first slot

**Comment by quiqueck** [comment]
Fixed in release 2.0.4
