### ISSUE TITLE
[Bug] Crystals not spawning in Crystal Mountain Biomes

### ISSUE THREAD

**Issue by RiskE80T** [quiqueck/BetterEnd#19]
### What happened?

entered crystal mountain biomes and none of them had any crystals, assuming this is a bug

### BetterEnd

2.0.2

### BCLib

2.0.5

### Fabric API

0.56.3

### Fabric Loader

0.14.8

### Minecraft

1.19

**Comment by quiqueck** [comment]
Sound be fixed in the just release 2.0.3 Version
