### ISSUE TITLE
[Bug] Barrel closing sound is played immediately after the opening sound is played.

### ISSUE THREAD

**Issue by spinodal23** [quiqueck/BetterEnd#20]
### What happened?

As can be seen in the image below, when I open the barrel, "Barrel opens" sound is played correctly.
However, the "Barrel closes" sound is also played right after the "Barrel opens" sound is played even if I am still opening the barrel.
This bug does not appear when using vanilla barrel; only appear when using BetterEnd barrels.

![image](https://user-images.githubusercontent.com/96723542/175945090-36cd1b14-9696-4871-8c9e-afa4e614d740.png)

### BetterEnd

2.0.2

### BCLib

2.0.5

### Fabric API

0.56.3

### Fabric Loader

0.14.8

### Minecraft

1.19

**Comment by quiqueck** [comment]
Fixed in BCLib 2.0.7
