### ISSUE TITLE
Making "Berry Jelly" should return empty Glass Bottle.

### ISSUE THREAD

**Issue by spinodal23** [quiqueck/BetterEnd#21]
### What happened?

When making "Sweet Berry Jelly" and "Blossom Berry Jelly", the Water Bottle is totally consumed as can be seen in the following images. I think the Water Bottle in the crafting table should be replaced with Glass Bottle when the Jellies are made.

![image](https://user-images.githubusercontent.com/96723542/175950145-91f3d259-2677-42cd-b164-d9485a0eec76.png)

![image](https://user-images.githubusercontent.com/96723542/175950272-ca4d60cf-365b-4e36-a0ad-530be0f11db5.png)

I was not able to check whether this bug also appear for the "Shadow Berry Jelly" because I don't know the crafting recipe for that right now. (I mean, right now I didn't put REI mod yet so I couldn't check for the recipe. But in the past, in 1.18.1, the crafting recipe of Shadow Berry Jelly was not present in REI.)

![image](https://user-images.githubusercontent.com/96723542/175953154-89d6ac1a-35e6-4a76-8362-032419ba03e4.png)

### BetterEnd

2.0.2

### BCLib

2.0.5

### Fabric API

0.56.3

### Fabric Loader

0.14.8

### Minecraft

1.19

**Comment by spinodal23** [comment]
Additional info: in 1.19, the crafting recipe of Shadow Berry Jelly does not appear in REI. Also, assuming the recipe pattern of the other two jellies, when I try to put the item "shadow_berry_raw" or "shadow_berry_cooked" instead of other berries, it does not return anything. Maybe the recipe of Shadow Berry Jelly is missing? Anyway, thank you for this great mod!

**Comment by FalseJ** [comment]
![image](https://user-images.githubusercontent.com/110573620/182731231-6cefb71a-92c3-40a1-9a36-761adcb17717.png)
I meet the same problem when trying to make the shadow berry jelly! no matter using the cooked one or the raw one, I can't make them.

Then I try to unzip the mod to find recipe, and then I find this (We're playing in a 1.18.1 server so we're using the BetterEnd 1.0.1.jar, but i find this in BetterEnd 1.1.1.jar too)
I don't know much about fabric mods yet, but maybe this causes the issue...?

(really love this mod! Me and my friends made a BetterEnd Museum in our server and write stories about it!)

**Comment by quiqueck** [comment]
Jep, that is what 6c72036dd6530b08eacf358b84013fd2f1a41f0c did fix :)
