### ISSUE TITLE
[Bug] the new end cities won't spawn

### ISSUE THREAD

**Issue by benbenbenbenbenbenbenbenbenbenbenbenbe** [quiqueck/BetterEnd#22]
### What happened?

i've been playing for a while now and the only end cities I come across are the normal ones 

### BetterEnd

2.0.2

### BCLib

2.0.5

### Fabric API

0.56.3

### Fabric Loader

using curseforge launcher but I created a custom profile in the launcher and made it fabric

### Minecraft

1.19

**Comment by quiqueck** [comment]
Thanks for reporting, but I am not sure which "new End Cities" you mean? The crashed Ships?

BetterEnd itself does not add new End Cities...

**Comment by benbenbenbenbenbenbenbenbenbenbenbenbe** [comment]
> 

I mean the upgraded ones, with the blimps and the cooler looking end cities

**Comment by quiqueck** [comment]
I think that was an additional DataPack for BetterEnd. Not sure if it was ported to 1.19 tho...

**Comment by benbenbenbenbenbenbenbenbenbenbenbenbe** [comment]
> I think that was an additional DataPack for BetterEnd. Not sure if it was ported to 1.19 tho...

okay, so what was the datapack?

**Comment by quiqueck** [comment]
Probably "Better End City" by IchPhilipp
