### ISSUE TITLE
[Bug] [1.20] Unable to mine certain blocks with any pickaxe

### ISSUE THREAD

**Issue by Hexze** [quiqueck/BetterEnd#224]
### What happened?

I added the new BetterEnd alpha for 1.20 to my survival world. When I arrived in the end, I found that many of the new terrain blocks added by the mod (Flavolite, Amber Moss, End Moss, Shadow Grass, etc.) were unable to be mined. They can be destroyed, but it takes a long time and no item is dropped.

### BetterEnd

4.0.0

### BCLib

3.0.5

### Fabric API

0.83.0

### Fabric Loader

0.14.21

### Minecraft

1.20.0

**Comment by Hexze** [comment]
Was happy to see how swiftly the alpha for 1.20 was put out, this is one of my favorite mods :)

**Comment by quiqueck** [comment]
Thanks for reporting. Fix will be in the next update.

**Comment by quiqueck** [comment]
Release with 4.0.2. Please re-open this issue if there are still problems.
