### ISSUE TITLE
[Spelling Error] "Netherite Hammer Upgrade Template" Tooltip

### ISSUE THREAD

**Issue by Chrizzx3** [quiqueck/BetterEnd#225]
### What happened?

In the Tooltip for the Smithing Template "Netherite Hammer Upgrade Template", Netherite is spelled wrongly as "Netehrite".
![Netherite Hammer Upgrade](https://github.com/quiqueck/BetterEnd/assets/92762855/fd76f96b-dccf-4b32-a486-933c70a4c739)

### BetterEnd

4.0.1

### BCLib

3.0.5

### Fabric API

0.83.1+1.20.1

### Fabric Loader

0.14.21

### Minecraft

1.20.1

**Comment by quiqueck** [comment]
Thanks for the report. Fix will be included in the next update.

**Comment by quiqueck** [comment]
Release with 4.0.2. Please re-open this issue if there are still problems.
