### ISSUE TITLE
[Bug] Small Jellyshroom displaced/detached from block when connected from side

### ISSUE THREAD

**Issue by Chrizzx3** [quiqueck/BetterEnd#226]
### What happened?

The "Small Jellyshroom" is, depending on the location of the log/block it attaches to from the side, detached/wrongly displaced.
This displacement is sometimes less visible and sometimes as big as in the pictures.
![Small Jellyshroom Displacement 2](https://github.com/quiqueck/BetterEnd/assets/92762855/4f50f88f-6128-46e9-b50a-02d320a85dfd)
![Small Jellyshroom Displacement 1](https://github.com/quiqueck/BetterEnd/assets/92762855/6838ce82-b949-47f9-b997-206b2ed2f535)

### BetterEnd

4.0.1

### BCLib

3.0.5

### Fabric API

0.83.1+1.20.1

### Fabric Loader

0.14.21

### Minecraft

1.20.1

**Comment by quiqueck** [comment]
Thanks for reporting, will be in the next update.

**Comment by quiqueck** [comment]
Release with 4.0.2. Please re-open this issue if there are still problems.
