### ISSUE TITLE
[Bug] Certain plants/mushrooms/moss make wrong block place/destroy sound 

### ISSUE THREAD

**Issue by Chrizzx3** [quiqueck/BetterEnd#227]
### What happened?

Certain plants/mushrooms/moss have the default "stone" break/place sound. Taken and tested out from creative menu tab "BetterEnd: Plants". This includes:

Cave Grass
Crystal Grass
Shadow Plant
Bushy Grass
Amber Grass
Twisted Umbrella Moss
Jungle Grass
Blooming Cooksonia
Salteago
Vaiolush Fern
Fracturn
Clawfern
Globulagus
Small Amaranita Mushroom
Orango
Aeridium
Lutebus
Lamellarium
Bolux Mushroom
Inflexia
Flammalix
Tail Moss
Cyan Moss
Twisted Moss
Bulb Moss
Jungle Fern
Ruscus

This may be design choice for some, but considering all of these are categorized as plants, I'm going to assume they should make a different sound and therefore mark this as a bug/error. All plants listed can be seen in this screenshot:

![All plants with wrong sound](https://github.com/quiqueck/BetterEnd/assets/92762855/9856e266-c52b-46ce-b45d-6cf6f5524b87)

### BetterEnd

4.0.1

### BCLib

3.0.5

### Fabric API

0.83.1+1.20.1

### Fabric Loader

0.14.21

### Minecraft

1.20.1

**Comment by quiqueck** [comment]
Will get release with BCLib 3.0.7 (sorry, I saw the report too late for the just released 3.0.6)
