### ISSUE TITLE
[Bug] Betterend's discs disappear on jukebox

### ISSUE THREAD

**Issue by aoligei635** [quiqueck/BetterEnd#230]
### What happened?

When I right clicked the jukebox with Betterend's discs,they disappered and the jukebox didn't play music.

### BetterEnd

4.0.3

### BCLib

3.0.7

### Fabric API

0.83.0

### Fabric Loader

0.14.21

### Minecraft

1.20.0

**Comment by quiqueck** [comment]
Thanks for reporting. I'll have a look...

**Comment by quiqueck** [comment]
Should be fixed in 4.0.4. Please let me know if you still have issues with this.
