### ISSUE TITLE
[Suggestion] [1.20] Silk touch pickaxe has no effect on sulfur crystals

### ISSUE THREAD

**Issue by Hexze** [quiqueck/BetterEnd#231]
### What happened?

Sulfur crystals drop the sulfur item whether they are mined with a normal pickaxe or silk touch one

### BetterEnd

4.0.3

### BCLib

3.0.7

### Fabric API

0.83.0

### Fabric Loader

0.14.21

### Minecraft

1.20.0

**Comment by quiqueck** [comment]
Thanks for the report, I'll change it to a suggestion as this was the intended behaviour.

**Comment by quiqueck** [comment]
Should be added in 4.0.4. Please let me know if you still have issues with this.
