### ISSUE TITLE
[Bug] [1.20] Eternal Portals generate too frequently?

### ISSUE THREAD

**Issue by Hexze** [quiqueck/BetterEnd#232]
### What happened?

Not sure if this is a bug per se, but Eternal Portals seem to generate far too often. I found 3 all within 100 blocks of eachother.

### BetterEnd

4.0.3

### BCLib

3.0.7

### Fabric API

0.83.0

### Fabric Loader

0.14.21

### Minecraft

1.20.0

**Comment by quiqueck** [comment]
Thanks for the report. You are right, they are created way to close. I'll update the generation.

**Comment by quiqueck** [comment]
Should be fixed in 4.0.4. Please let me know if you still have issues with this.
