### ISSUE TITLE
[Bug] Crashes with Patchouli 

### ISSUE THREAD

**Issue by xXRinzlerrXx** [quiqueck/BetterEnd#233]
### What happened?

crashes with Patchouli v 79 fabric

version 3.2.2 works fine

### BetterEnd

3.2.3

### BCLib

2.3.3

### Fabric API

0.83.0

### Fabric Loader

0.14.21

### Minecraft

1.19.4

**Comment by quiqueck** [comment]
Should be fixed with the just released 3.2.4
