### ISSUE TITLE
[Bug] Player is rendered transparent

### ISSUE THREAD

**Issue by xXRinzlerrXx** [quiqueck/BetterEnd#235]
### What happened?

something interesting is happening with the textures in the ender, which for some reason is transparent, through it you can view objects that are also transparent, as well as through objects in your hands

the mod was tested on a clean version of the game, an improved first-person view was added for clarity screenshots

this does not happen in hell and the upper world
![2023-06-19_08 45 09](https://github.com/quiqueck/BetterEnd/assets/135618265/1655f1e6-cf6e-49c8-a8e6-3ca0c8a1414e)
![2023-06-19_08 46 07](https://github.com/quiqueck/BetterEnd/assets/135618265/ca3b3f21-0fb8-4e73-b110-72f3ddad135c)
![2023-06-19_08 46 14](https://github.com/quiqueck/BetterEnd/assets/135618265/ed87f097-edd3-490b-b14e-8e95698939da)
![2023-06-19_08 38 54](https://github.com/quiqueck/BetterEnd/assets/135618265/38343ebb-a413-4855-8ab1-76cfbca388b2)
![2023-06-19_08 38 57](https://github.com/quiqueck/BetterEnd/assets/135618265/49be9791-f103-4a4f-bb16-46db23b2eb0c)
![2023-06-19_08 39 03](https://github.com/quiqueck/BetterEnd/assets/135618265/216309c2-0266-4e1e-abbb-e64e1095ff15)
![2023-06-19_08 44 00](https://github.com/quiqueck/BetterEnd/assets/135618265/01774876-8357-4586-9352-e2ee5d7c5c14)
![2023-06-19_08 44 05](https://github.com/quiqueck/BetterEnd/assets/135618265/18e885c0-01e1-4425-b0f9-69af90d279cd)
![2023-06-19_08 44 43](https://github.com/quiqueck/BetterEnd/assets/135618265/9e7e5c77-fd63-4350-9f86-862d15d252ad)

### BetterEnd

3.2.4

### BCLib

2.3.4

### Fabric API

0.83.0

### Fabric Loader

0.14.21

### Minecraft

1.19.4

**Comment by quiqueck** [comment]
Should be fixed in BetterEnd 4.0.5. Please re-open the issue if you still experience Problems.

**Comment by xXRinzlerrXx** [comment]
It's for 1.20.1, and I'm playing on 1.19.4

or can the mod version 4.0.5 run on 1.19.4?
