### ISSUE TITLE
[Bug] Eternal Portal only works in creative mode

### ISSUE THREAD

**Issue by SylvaGamer** [quiqueck/BetterEnd#239]
### What happened?

Whenever I go through an eternal portal in survival and stand there for a few minutes nothing happens. I tried this in creative mode and it worked right away. Switched back to survival and nothing. I tried this on Server and survival running multiple mods and just Better X mods, the same thing still happens.

### BetterEnd

4.0.4

### BCLib

3.0.8

### Fabric API

0.83.0

### Fabric Loader

0.14.21

### Minecraft

1.20.0

### Other Mods

```shell
Better Nether 9.0.5
```

**Comment by quiqueck** [comment]
Should work in BetterEnd 4.0.5. Please re-open the issue if the problem was not fixed.

**Comment by SylvaGamer** [comment]
Can confirm the issue is fixed in 4.0.5
