### ISSUE TITLE
[Bug] Moss is offsetted

### ISSUE THREAD

**Issue by paulevsGitch** [quiqueck/BetterEnd#24]
### What happened?

Some moss variants are offsetted from normal position and can be inside/outside of other blocks

![2022-06-30_14 59 00](https://user-images.githubusercontent.com/17707380/176672141-ae41172c-2f89-4577-a08d-f9eb1b07df3e.png)

### BetterEnd

2.0.3

### BCLib

2.0.6

### Fabric API

0.56.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Other Mods

```shell
better-nether-7.0.3
eden-ring-0.6.3
enderscape-0.3.0
geckolib-fabric-1.19-3.1.2
iris-mc1.19-1.2.5
mantori-1.1.0-1.19
modmenu-4.0.0
sodium-fabric-mc1.19-0.4.2+build.16
worldedit-mod-7.2.11-beta-01
```

**Comment by quiqueck** [comment]
Fixed in 2.0.4
