### ISSUE TITLE
[Bug] Grass block in end village house

### ISSUE THREAD

**Issue by ChristopherJ123** [quiqueck/BetterEnd#244]
### What happened?

I think grass block shouldn't generate in the end village, rather use end mycelium/grass blocks.
![2023-06-23_00 32 17](https://github.com/quiqueck/BetterEnd/assets/86960084/b03d6b78-b829-48db-b0e7-5188e9d3135a)

### BetterEnd

4.0.6

### BCLib

3.0.9

### Minecraft

1.20.1

**Comment by quiqueck** [comment]
That was actually intentional, as Enderman collect grass blocks from the overworld :)
