### ISSUE TITLE
[Bug] Cubozoa and endfish doesn't spawn in certain biomes

### ISSUE THREAD

**Issue by ChristopherJ123** [quiqueck/BetterEnd#245]
### What happened?

I have noticed that Cubozoa and End fish does not spawn in sulfur springs, umbrella jungle, amber land, etc, (i've seen it spawn normally in megalake biome, and rarely in Foggy Mushroomland biome). My difficulty is normal.

### BetterEnd

4.0.6

### BCLib

3.0.9

### Minecraft

1.20.1

**Comment by quiqueck** [comment]
Thnaks again for reporting, I think this was an issue with the mob cast, especially the huge search are we did use. I think more mobs will spawn in the next release.

**Comment by quiqueck** [comment]
Should be better in BetterEnd 4.0.7

**Comment by LunelleVatrinea** [comment]
I'd love to see this change implemented in a 1.19.2 release, as that is the version I personally use for mods. After testing 4.0.7, it did indeed fix it up nicely for 1.20.1
