### ISSUE TITLE
[Bug] Texture name containing space

### ISSUE THREAD

**Issue by gkr0013** [quiqueck/BetterEnd#251]
### What happened?

Dear,

The space in the file name (betterend\textures\item\thermal fungus.png) is still present in version 4.0.7 (1.20.1); like "Texture name containing space (https://github.com/quiqueck/BetterEnd/issues/148)"

### BetterEnd

4.0.7

### BCLib

3.0.10

### Fabric API

0.84.0+1.20.1

### Minecraft

1.20.1

**Comment by quiqueck** [comment]
This should be fixed with BetterEnd 4.0.8. Please re-open the issue if the problem was not solved for you.
