### ISSUE TITLE
Very Bizarre Bug

### ISSUE THREAD

**Issue by dogman309** [quiqueck/BetterEnd#253]
### What happened?

I'm using BetterEnd along side several other mods, but I don't think those are causing the issue I am having. So the first time I fought the dragon all was fine, then when I went to respawn the dragon... Things got a bit weird. For some reason the portal duplicated itself 2-3 blocks higher, and all the towers did the same but much higher. I tried recreating on a fresh world with all the same mods and could not get the bug to happen again. When I tried on a duplicate world save, however, it did work. I did it 3 times before they stopped duplicating. There was also a weird patch of floating experience orbs above the portal, not sure why. I'll attach a few screenshots
![mods](https://github.com/quiqueck/BetterEnd/assets/135499242/cd50bb1d-7f7b-417e-8f26-d9db6134e7af)
![2023-06-28_19 59 47](https://github.com/quiqueck/BetterEnd/assets/135499242/6341a25b-8d75-46a9-8bb6-5ae778af55da)
![2023-06-28_19 40 48](https://github.com/quiqueck/BetterEnd/assets/135499242/2bc00f99-3b03-4839-83c2-9c6f8dfb03e3)

### BetterEnd

2.1.6

### BCLib

2.1.7

### Fabric API

quilted fabric api 4.0.0-beta.30

### Fabric Loader

quilt 0.18.10

### Minecraft

1.19.2

**Comment by quiqueck** [comment]
Thanks for reporting, could you please post the seed of the world?
