### ISSUE TITLE
[Bug] Anvil logic for shift+click causes premature break

### ISSUE THREAD

**Issue by purejosh** [quiqueck/BetterEnd#259]
### What happened?

The anvils from BE have an odd logic about them, if you're using a shift+click to process a large number of items. 

I'll provide an example. When making ender dust, I was able to get 32 of them and cause 10% damage to my thallisum anvil. But, in my aeternium anvil with 24% damage, I shift clicked 32 through it and it broke.

It breaks exponentially faster if you shift click items through it, instead of one by one.

### BetterEnd

2.1.6

### BCLib

2.1.7

### Fabric API

0.76.0

### Fabric Loader

0.14.21

### Minecraft

1.19.2

**Comment by quiqueck** [comment]
This should behave differently in BetterEnd 4.0.8. Please re-open the issue if the problem was not solved for you.
