### ISSUE TITLE
[Bug] Incompatibility with BYG

### ISSUE THREAD

**Issue by clmc99** [quiqueck/BetterEnd#28]
### What happened?

With both BE and BYG loaded, most biomes from both mods don't generate and there's some weird far lands stuff going on. Tested with only the latest versions of BCLib, BE, Fabric API, BYG and Terrablender loaded, configs deleted before testing. I see BE ores and rocks and an ice starfield nearby, but nothing else as far as I can tell from where I've looked so far; most biomes cannot be found with /locate biome. Doesn't happen with only Terrablender (without BYG)

![2022-07-02_23 46 54](https://user-images.githubusercontent.com/85983330/177024897-8aed25f7-4ebe-47f0-adac-56966d29ff00.png)
![2022-07-02_14 47 21](https://user-images.githubusercontent.com/85983330/177024895-d3321558-0404-4006-a2c6-0a9a1c9d5323.png)
![2022-07-02_14 54 21](https://user-images.githubusercontent.com/85983330/177024896-1afa27b3-2360-4fef-a87b-4b2ce8b39398.png)
.

### BetterEnd

2.0.4

### BCLib

2.0.9

### Fabric API

0.57.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Other Mods

```shell
Fabric API
BYG
Terrablender
```

**Comment by quiqueck** [comment]
Could you please post your logs?

**Comment by quiqueck** [comment]
For Reference:
AOCAWOL/BYG/issues/836

**Comment by quiqueck** [comment]
Should be fixed with the next update for BCLib (2.0.10)

**Comment by clmc99** [comment]
Still want the log?

**Comment by quiqueck** [comment]
Nope. But thanks for checking back. :)

**Comment by quiqueck** [comment]
New version was just uploaded to CourseForge. Thanks again for reporting the issue :)
