### ISSUE TITLE
[Bug] BYG end biomes can't be found using BetterX world type

### ISSUE THREAD

**Issue by clmc99** [quiqueck/BetterEnd#29]
### What happened?

With the latest releases of BetterEnd and BCLib, there are no chunk errors, but no BYG end biomes can be located with /locate biome when using the BetterX world type. With the Default world type, biomes from both mods are present, but there are some other issues. The first time I tried to fly around in the end, my game crashed (log below); when I loaded back into the world, the game did not crash, but I noticed a weird biome border (image below). Also reported in [AOCAWOL/BYG#836](https://github.com/AOCAWOL/BYG/issues/836)

[2022-07-03-6.log](https://github.com/AOCAWOL/BYG/files/9035391/2022-07-03-6.log)

![2022-07-03_15 23 34](https://user-images.githubusercontent.com/85983330/177054575-94d99ce2-8451-4475-97a4-e84b2da7e856.png)

### BetterEnd

2.0.5

### BCLib

2.0.10

### Fabric API

0.57.0

### Fabric Loader

0.14.8

### Minecraft

1.19

### Relevant log output

```shell
Attached
```

### Other Mods

```shell
Fabric API
BYG
Terrablender
```

**Comment by quiqueck** [comment]
I did resolve the first issue (betterx-preset not including big biomes) Do you have the seed and location for the screenshot you posted above?

**Comment by clmc99** [comment]
5571816661705559297 at 300, -1100. Cool overworld seed in vanilla—dark forest with tons of mountains and lush caves, woodland mansion close to spawn

**Comment by quiqueck** [comment]
Should be fixed with the just released BCLib 2.0.11.
