### ISSUE TITLE
[Suggestion] Forge?

### ISSUE THREAD

**Issue by SafeOfArsenal** [quiqueck/BetterEnd#291]
### Description

What is BetterNether on forge but not BetterEnd? These mods would be perfect togther

**Comment by NolanHewitt** [comment]
BetterNether is not available on modern minecraft for forge.

**Comment by nikallow** [comment]
BetterX Mods (The official discord server of the BetterEnd mod)
FAQ: 
1.  __Where I can get Forge version?__
Official Forge version existed only for 1.12 (only for BetterNether), you can get it from mod Curseforge page from files section. All other ports are not official.
If you are using outdated version from Beethoven (BetterEnd) - he stopped working on it and left without a trace. Our team members tried to contact him during some months without any success. We are not working on Forge ports and we are not interested in progress of unofficial ports - our jib is not about telling other independent developers what they should do.
2. __Why there are no Forge version for 1.13+? Will they appear?__
We are not working with Forge anymore, there are no plans for official Forge versions of our mods. Forge and Fabric have different architecture and supporting large mods for both versions is almost impossible for a small team.
