### ISSUE TITLE
End Stone Smelter hopper interaction

### ISSUE THREAD

**Issue by Flyvee** [quiqueck/BetterEnd#30]
### Description

Currently the end stone smelter interacts with hopper in that a hopper from the top fills in the 2nd slot, hopper from the sides fill in first the 2nd then the fuel slot and a hopper at the bottom is the output slot. I suggest that the front and back sides of the smelter be specialized for the 2nd and fuel slots, e.g. the back side of the smelter fills in the 2nd slot and the front side fills in the fuel slot as currently if the 2nd slot's hopper runs empty but the fuel side's hopper doesn't, then the fuel fills up the 2nd slot instead which breaks the smelting chain.

**Comment by quiqueck** [comment]
I would suggest the following (similar to vanilla) behavior:
Top -> Both Ingredient slots
Bottom -> Result
Sides -> Fuel

**Comment by quiqueck** [comment]
The new release (2.0.7) contains the hopper changes I mention above. Please re-open this issue if you would still recommend more changes
