### ISSUE TITLE
When I go somewhere in the nether of the server, the client will crash.[Bug] 

### ISSUE THREAD

**Issue by AyMeow** [quiqueck/BetterEnd#31]
### What happened?

Hello developer! Thank you for your active recovery last time, but I found that some problems are still very serious, the compatibility of c2memod is still not effective, and the flash back problem I mentioned this time.
This is a crash report：https://mclo.gs/EGlJruB

### BetterEnd

2.0.5

### BCLib

2.0.10

### Fabric API

0.57.0

### Fabric Loader

0.14.8

### Minecraft

1.19

**Comment by quiqueck** [comment]
Thanks for reporting. Is this a random issue or does it crash on a specific action?

**Comment by AyMeow** [comment]
> Thanks for reporting. Is this a random issue or does it crash on a specific action?

Oh, I used velocity when I found the problem; When I abandoned velocity, this problem didn't seem to happen, but the new problem is that players don't load the world after coming out of hell, and even can only restart the game.

**Comment by AyMeow** [comment]
> Thanks for reporting. Is this a random issue or does it crash on a specific action?

I also found an interesting problem. When I recreate the archive and use it with c2me, it has good compatibility. However, when I join the server halfway, the previous situation will still occur, even if I use the latest version of "bclib" and "betterend"

**Comment by AyMeow** [comment]
> Thanks for reporting. Is this a random issue or does it crash on a specific action?

In addition, I'm not sure whether the client crashes randomly or at a certain location. Some players report that flying in nether will suddenly crash. Of course, this is the case when velocity is used. After removal, it seems that this problem does not appear anymore. At present, the client will not respond when entering or leaving hell gate. I'm not sure if it's the loading problem of "betterx"

**Comment by Anoxia-Cat** [comment]
> Thanks for reporting. Is this a random issue or does it crash on a specific action?

In addition, I'm not sure whether the client crashes randomly or at a certain location. Some players report that flying in nether will suddenly crash. Of course, this is the case when velocity is used. After removal, it seems that this problem does not appear anymore. At present, the client will not respond when entering or leaving hell gate. I'm not sure if it's the loading problem of "betterx"

**Comment by quiqueck** [comment]
While we try to work with c2me we do not officially support it. Some parts of our code are designed to be fast, but single threaded. That part will randomly glitch for c2me users. While new code is designed to work across multiple parallel threads,  older code probably won't.

For the crash you posted: I think I have a solution for that specific problem. But I am not sure if the other crashes are related to that or to c2me.

**Comment by AyMeow** [comment]
> 虽然我们尝试与 c2me 合作，但我们并未正式支持它。我们代码的某些部分设计为快速但单线程。对于 c2me 用户，该部分会随机出现故障。虽然新代码旨在跨多个并行线程工作，但旧代码可能不会。
> 
> 对于您发布的崩溃：我想我有针对该特定问题的解决方案。但我不确定其他崩溃是否与此有关或与 c2me 有关。

Oh, I don't use c2me anymore. I've removed c2me since the last crash. When you release the update, I just test it slightly. It seems that it should be OK, but I probably have to recreate the archive. But anyway, I will always support "bclib" and "betterend"! At present, the problem of hell gate is causing trouble. Although it does not have a great impact on the overall game, it is still not very friendly to the player experience: P

**Comment by quiqueck** [comment]
Thanks for your support :)

Hopefully the implemented fix solves the nether portal issue.

**Comment by AyMeow** [comment]
> 谢谢你的支持 ：）
> 
> 希望实施的修复解决了下界门户问题。

Anyway, thank you for your positive reply and look forward to your update! You are the fastest developer I have ever seen. Hahaha!

**Comment by AyMeow** [comment]
> Thanks for your support :)
> 
> Hopefully the implemented fix solves the nether portal issue.

Oh, there's another problem. When the "better end" items are placed on the upper layer of nether's bedrock and then removed, the original position will produce a perspective effect. It seems that pictures can't be sent here. I'll post pictures in the comment area of curseforge.

**Comment by quiqueck** [comment]
You can post images here as well

**Comment by AyMeow** [comment]
> You can post images here as well

[https://s1.ax1x.com/2022/07/08/jBhz6O.png](url)
Like this

**Comment by quiqueck** [comment]
I think you can drag&drop the image the comment as well

**Comment by AyMeow** [comment]
> 



> 我认为您也可以将图像放到评论中

oh！！！alright.
![61L0)@_{K@KVV@7M%6 5NP8](https://user-images.githubusercontent.com/101166982/177969124-6736540c-6bb0-44cd-8685-6d891bad9b67.png)
.

**Comment by quiqueck** [comment]
This looks more like a rendering issue which is probably not directly related to BetterEnd. Do you have any client-side rendering mods installed (or mods that optimize the rendering performance like sodium or indium)?

**Comment by AyMeow** [comment]
> 这看起来更像是一个可能与 BetterEnd 没有直接关系的渲染问题。您是否安装了任何客户端渲染模块（或优化渲染性能的模块，如钠或铟）？

Yes, but all players have installed sodium, but I'm not sure whether this player has installed other rendering mods. I need to check it. Indeed, some players do not have this problem.

**Comment by AyMeow** [comment]
> nether portal

ok.... Just re-enter the nether portal. Sorry to trouble you :x

**Comment by AyMeow** [comment]
> This looks more like a rendering issue which is probably not directly related to BetterEnd. Do you have any client-side rendering mods installed (or mods that optimize the rendering performance like sodium or indium)?

look at this：https://mclo.gs/inOQEiX
I also encountered that rendering problem. After I re entered, although the rendering was restored, when I right clicked other players and placed them on the pedestals on the upper layer of nether, my client crashed, and the area where pedestals were located also happened to be the area with rendering problems Crash log when above.

**Comment by AyMeow** [comment]
> This looks more like a rendering issue which is probably not directly related to BetterEnd. Do you have any client-side rendering mods installed (or mods that optimize the rendering performance like sodium or indium)?

I tested it!! It's the problem of "pedals" or "end stone smelter". When I destroy these two items, the area returns to normal! So please be sure to check these two squares!

**Comment by quiqueck** [comment]
The crash is due to the bug that should be fixed in the next version.

But the rendering issue is most likely due to another mod (or in other words, I can not reproduce that behavior). That could be a mod that improves rendering or general performance.

**Comment by AyMeow** [comment]
> The crash is due to the bug that should be fixed in the next version.
> 
> But the rendering issue is most likely due to another mod (or in other words, I can not reproduce that behavior). That could be a mod that improves rendering or general performance.

Looking forward to the next version!

**Comment by quiqueck** [comment]
Should be fixed with the just released BCLib 2.0.11.
