### ISSUE TITLE
[Bug] No loot in wrecked end ship

### ISSUE THREAD

**Issue by xNorcia** [quiqueck/BetterEnd#315]
### What happened?

First time using this mod, so I head into creative to play around with it. Kill the dragon bla bla bla. Go through and end gateway. Find a wrecked end ship (idk the name of it), so I dig it out to see what kind of loot is generated. Find the chests and they be empty. Not sure if this is an intended feature or not but I'm assuming it isn't.

ps: incantationem enchantments wont apply to the armours / tools in either better end or better nether, though whether that's their problem or yours idk

### BetterEnd

4.0.10

### BCLib

3.0.13

### Fabric API

0.90.7

### Fabric Loader

0.14.24

### Minecraft

1.20.1

### Other Mods

```shell
Airhop, Appleskin, Architectuary, Bartering Station, Better Nether, Better Trees, Better Tridents, Cloth Config, Collective, Companion, Choice Theorems Overhauled Villages, Easy Anvils, Easy Magic, Easy Shulker Boxes, Elytra Physics, Fabric API, Falling Leaves, Forge Config API Port, Horse Expert, Incantationem, Iris, Just Enough Items, Lamb Dynamic Lights, Lithium, Logical Zoom, Mob Plaques, Mod Menu, Owo Lib, Puzzles Lib, Piercing Paxels, Sky Villages, Sodium, Starlight, Tiny Item Animations, Tidal Towns, Trading Post, Tree Harvester, Villager Names, Visual Workbench, Wavey Capes, Wraith Waystones, Xaeros World Map, Xaeros Minimap.
```

**Comment by paulevsGitch** [comment]
This is not a bug, crashed End ships don't have loot
