### ISSUE TITLE
[Bug] Furnace will erase resultant items if you click a recipe

### ISSUE THREAD

**Issue by purejosh** [quiqueck/BetterEnd#32]
### What happened?

If you have items in the resultant slot of the ender furnace, and click a recipe on the left screen, your items will be erased from the furnace instead of being sent to your inventory. Unconfirmed what the behavior of the input slots are, I did not test that with recipe clicking. 

### BetterEnd

better-end-1.1.1

### BCLib

bclib-1.4.7

### Fabric API

fabric-api-0.57.0+1.18.2

### Fabric Loader

0.14.8

### Minecraft

1.18.2

**Comment by quiqueck** [comment]
Thanks for reporting. Will be fixed in the next release for 1.19

**Comment by quiqueck** [comment]
Should be fixed in 2.0.7
