### ISSUE TITLE
[Bug] recipe coflict with vanilla

### ISSUE THREAD

**Issue by ChaoscatCJ** [quiqueck/BetterEnd#328]
### What happened?

for some reason when making an iron block it makes a thalassium block instead

### BetterEnd

4.0.11

### BCLib

3.0.14

### Minecraft

1.20.1

**Comment by andr9528** [comment]
Do you per-chance also have 'Almost Unified'?

**Comment by paulevsGitch** [comment]
It's wrong interaction with Almost Unified, use this config as fix

![image](https://github.com/quiqueck/BetterEnd/assets/17707380/e733016f-360f-4719-9705-0ea6cbbc8195)
