### ISSUE TITLE
[Bug] Dragon not respawning

### ISSUE THREAD

**Issue by LyttleBeast** [quiqueck/BetterEnd#369]
### What happened?

I try an repawn the dragon and it just won't respawn. I tried all different varations of ender crystal placements and it just wont respawn. Everything else works fine except respawning the dragon. 

### BetterEnd

4.30.1

### BCLib

3.30.1

### Fabric API

0.96.4+1.20.4

### Fabric Loader

0.15.7

### Minecraft

1.20.4

### Relevant log output

```shell
https://mclo.gs/GSpVq7A
```

### Other Mods

```shell
This are the mods running on the server. 
BcLib
better-end
Bosses of mass destruction
cardinal-components-api
cloth-config
dungeons and taverns
dynamic lights
fabric api
fabric-language-kotlin
falling trees
geckolib
more mobs
spellbound weapons
tectonic
terralith
true ending (idk if this is it, this redoes the dragon fight)
vcinteraction
voicechat
```

**Comment by jrjespersen** [comment]
I also have this issue. I built a new profile with only the BetterEnd mod, killed the dragon, and cannot respawn it (tried multiple end crystal placements, including the one shown at https://imgur.com/a/I6vi6m3).

BetterEnd: 4.30.1
BCLib: 3.30.1
Fabric API: 0.97.0+1.20.4
Fabric Loader: 0.15.11
Minecraft: 1.20.4

Log: [latest.log](https://github.com/quiqueck/BetterEnd/files/15288811/latest.log)

Other Mods: None

**Comment by LyttleBeast** [comment]
> I also have this issue. I built a new profile with only the BetterEnd mod, killed the dragon, and cannot respawn it (tried multiple end crystal placements, including the one shown at https://imgur.com/a/I6vi6m3).
> 
> BetterEnd: 4.30.1 BCLib: 3.30.1 Fabric API: 0.97.0+1.20.4 Fabric Loader: 0.15.11 Minecraft: 1.20.4
> 
> Log: [latest.log](https://github.com/quiqueck/BetterEnd/files/15288811/latest.log)
> 
> Other Mods: None

I got this to work by just resetting the end. Try deleting the DIM1 folder and then going back into the end. If it still doesn’t respawn you have to take the level.dat file into a nbt editor and change that variable that says whether or not the dragon had been encountered with. (This is what I did) and then change the number.
