### ISSUE TITLE
[Bug] I can't open the server in the new version!

### ISSUE THREAD

**Issue by AyMeow** [quiqueck/BetterEnd#38]
### What happened?

![微信截图_20220712083413](https://user-images.githubusercontent.com/101166982/178381497-3c35381a-0e08-4761-a94f-c0fedeb2bc30.png)

### BetterEnd

2.0.7

### BCLib

2.0.13

### Fabric API

0.57.0

### Fabric Loader

0.14.8

### Minecraft

1.19

**Comment by xIGBClutchIx** [comment]
Looks like commit f6df2a250450c01c12be886e37fadbcd4f49f0b0 broke it with it accessing a client-side only GUI.

**Comment by AyMeow** [comment]
> 看起来提交[f6df2a2](https://github.com/quiqueck/BetterEnd/commit/f6df2a250450c01c12be886e37fadbcd4f49f0b0)破坏了它，它访问了仅客户端的 GUI。

It seems that we can only wait for the repair

**Comment by quiqueck** [comment]
Oh, that somehow snuck in. Sorry :(

Just pushed a fixed version to CourseForge.

**Comment by AyMeow** [comment]
> Oh, that somehow snuck in. Sorry :(
> 
> Just pushed a fixed version to CourseForge.

The server can be turned on, but the furnace that turns on betterend will still crash

**Comment by AyMeow** [comment]
> Oh, that somehow snuck in. Sorry :(
> 
> Just pushed a fixed version to CourseForge.

https://mclo.gs/4mc7vCU

**Comment by quiqueck** [comment]
Thanks, I'll look into it right now

**Comment by quiqueck** [comment]
ok, pushed another update to 2.0.9

**Comment by AyMeow** [comment]
> ok, pushed another update to 2.0.9

Thank you for your update. Everything is stable at present！：D
