### ISSUE TITLE
[Bug] betterend:tail_moss with wrong direction and crashed the game

### ISSUE THREAD

**Issue by AresConnor** [quiqueck/BetterEnd#387]
### What happened?

explorer the end and the game suddenly crashed,
crash report (partial): https://pastebin.com/V4q6aF3w
full file:
[crash-2024-04-27_17.11.57-server.txt](https://github.com/quiqueck/BetterEnd/files/15137830/crash-2024-04-27_17.11.57-server.txt)

### BetterEnd

4.0.11

### BCLib

3.0.14

### Minecraft

1.20.1

### Other Mods

```shell
included in crash-report
```

**Comment by liangmoe** [comment]
Umm, sinytra issue should report to sinytra because betterend is intended to work on fabric loader, do you have redirector? Ive faced the similar issue before, remove it solve the problem, not sure if its work on yours

**Comment by AresConnor** [comment]
> Umm, sinytra issue should report to sinytra because betterend is intended to work on fabric loader, do you have redirector? Ive faced the similar issue before, remove it solve the problem, not sure if its work on yours

i removed redirector mod and it does work! thanks! :)
