### ISSUE TITLE
End for Dummies Not Craftable / Support for JEI

### ISSUE THREAD

**Issue by SapphireFox420** [quiqueck/BetterEnd#40]
### What happened?

We downloaded BetterEnd directly from CurseForge and the End for Dummies book is not showing up in JEI. We can not find a resource sharing how to create things on the Infusion Pedestal either so not sure how to use it. The Pedestal works to enchant after trial and error but the menu never shows up when trying to click on the Infusion Pedestal—just wondering if this is an issue or if those two features were removed and if so how do we find out how to use the Infusion Pedestal properly?

### BetterEnd

2.0.5

### BCLib

2.0.10

### Fabric API

0.57.0+1.19

### Minecraft

1.19

**Comment by quiqueck** [comment]
Hi, and thanks for contacting us :)

The (infusion-)pedestals do not have a screen that should show up, so that is normal. The book should be available if you have installed Patchouli.

**Comment by SapphireFox420** [comment]
Okay! We'll try downloading that mod. Thank you! I was confused thinking there was a menu that was supposed to appear due to this youtube video. Thanks again!
![image](https://user-images.githubusercontent.com/105528418/179118774-66606dd6-9b62-4eae-a8d2-0271920db7af.png)

**Comment by quiqueck** [comment]
That screen should show up in REI (and probably JEI, tho I do not test using JEI).

That image shows on which pedestal you need to place what item for a receipt to work.

**Comment by SapphireFox420** [comment]
Okay after you said that I was thinking that since I saw your recommended one was REI but it doesn't show up when using JEI. I appreciate the fast response though!
