### ISSUE TITLE
[Suggestion] 1.21 Support

### ISSUE THREAD

**Issue by Spike-has-no-idea-how-to-code** [quiqueck/BetterEnd#408]
### Description

I enjoy using better nether and better end, however upon updating to 1.21, I realized that Better End had not been updated with all the other mods. Maybe you guys are working on it, maybe you aren't, but I haven't seen anyone in issues ask for it, and the code hasn't had a new commit in half a year. This is mildly annoying specifically because I cannot play the game without Better End, as Minecraft can't boot up a world that has better end data inside. I simply have no way of knowing if this is being worked on so I had to make a suggestion about it just in case.

**Comment by Spike-has-no-idea-how-to-code** [comment]
Update: upon looking in the pull requests, I realized that 1.21 is in here somewhere, but this is a maze of forks that is insanely hard to navigate. I hail from modrinth, foolishly assuming that all the devs would use the same repo as the one that is linked at the actual download site. I have no idea what is going on, but i have a feeling that either the link takes you to the wrong fork or there is some spaghettification shenanigans happening

**Comment by Spike-has-no-idea-how-to-code** [comment]
Another update: I'm stupid its the same repo but i didnt realize it took me to 1.20.3 branch, sorry to have made this oops

**Comment by KennyDevT** [comment]
Do Not Compile the 1.21 branch it is unstable and broken for now. Please be patient.

**Comment by KennyDevT** [comment]
Nvm New version just released a few seconds ago.

**Comment by KennyDevT** [comment]
Nvm again new version is broken.

**Comment by Spike-has-no-idea-how-to-code** [comment]
are you referring to the deprecated gradle features error? just making sure i havent made a mistake

**Comment by KennyDevT** [comment]
No the mod it self is broken rn.

**Comment by Spike-has-no-idea-how-to-code** [comment]
oh well i cant build it, do you know how I can change gradle versions so that I'm not using the one that has deprecated the features this mod needs?

**Comment by KennyDevT** [comment]
that is not the issue you simply do not have the libraries and as i said please be patient and dont compile rn.

**Comment by OpenBagTwo** [comment]
Just FYI—if you want to build the mod yourself, you need to do the following:

1. Clone these *four* repos to and check out the following branches for each (making sure to use `--recurse-submodules` for WorldWeaver):
    - https://github.com/quiqueck/WunderLib at branch `feature/wover-1.21
    - https://github.com/quiqueck/WorldWeaver at branch `1.21`
    - https://github.com/quiqueck/BCLib at branch `1.21`
    - your own BetterEnd fork at your 1.21 branch
2. Make sure all four repos are in the same parent directory, _i.e._
    ```
    My Workspaces
    ├── BetterX
    |    ├── BCLib
    |    ├── BetterEnd
    |    ├── WorldWeaver
    |    ├── Wunderlib
    ```
3. Open BetterEnd in IntelliJ (or Eclipse or whatever), set up gradle, and run the build task
4. Copy the built mods from each repo's `build/libs` folder into your Minecraft instance

**Comment by KennyDevT** [comment]
Yeah ik its just that the mod is like broken rn some models straight dont render but your pr fixes that so i guess if he uses your pr he should be fine. And even at that he should wait for the wings to be fixed.

**Comment by OpenBagTwo** [comment]
Definitely do not recommend upgrading right now—looks like you can generate new worlds, but *old worlds* will be completely borked:

> [22:32:31] [Render thread/ERROR]: Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/chunk_generator]: bclib:betterx; Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/chunk_generator]: bclib:betterx missed input: {"minecraft:the_end":{biome_source:{config:{barrens_biomes_size:256,center_biomes_size:256,generator_version:"paulevs",inner_void_radius_squared:1048576,land_biomes_size:256,map_type:"hex",void_biomes_size:256,with_void_biomes:1b},seed:0L,type:"bclib:end_biome_source"},settings:"minecraft:end",type:"bclib:betterx"},"minecraft:the_nether":{biome_source:{config:{amplified:0b,biome_size:256,biome_size_vertical:86,map_type:"hex",use_vertical_biomes:1b},seed:0L,type:"bclib:nether_biome_source"},settings:"minecraft:nether",type:"bclib:betterx"}}

**Comment by KennyDevT** [comment]
And it crashes randomly too so def do update yet.
