### ISSUE TITLE
[Bug] BetterEnd crashes during server startup (but not client startup) 1.19.2

### ISSUE THREAD

**Issue by anticode-403** [quiqueck/BetterEnd#424]
### What happened?

Server crashes during startup. Nothing I've tried has fixed this thusfar, and I've confirmed that its not an issue with any of Moonlight's dependent mods.

### BetterEnd

2.1.7

### BCLib

2.1.8

### Fabric API

0.77.0

### Fabric Loader

0.15.11

### Minecraft

1.19.2

### Relevant log output

```shell
https://mclo.gs/yWAPGJq
```

**Comment by anticode-403** [comment]
I've also tried swapping out a lot of versions, for those situations where I can but that also has not seemed to help. Honestly, I can't find any reference to this function anywhere, even, so I'm very confused and frustrated with Java rn lol.

I should also clarify that I am certain this is an issue with BetterEnd, as the issue no longer persists when uninstalling the mod (which isn't really ideal at all)

**Comment by liangmoe** [comment]
You can get custom bclib from discord, that might be helpful

**Comment by anticode-403** [comment]
The custom bclib is version 2.1.8 which is what I'm using already. I have the exact same error. This is actually also the version uploaded on Modrinth, and the game starts up with BCLib installed but BetterEnd uninstalled, so this does appear to be an issue specific to BetterEnd 1.19.2.

**Comment by anticode-403** [comment]
So the error message is apparently due to Continuity (which I forgot to remove oops lol) but the server still crashes at the exact same point with BetterEnd installed.

**Comment by anticode-403** [comment]
Apparently this is an issue with TeamCommand, so I'm going to set off a grenade at my feet now.
