### ISSUE TITLE
[Bug] Unbreaking dosent work on chestplate elytras

### ISSUE THREAD

**Issue by HallowedPaladin** [quiqueck/BetterEnd#43]
### What happened?

When flying with a chestplate elytra, the unbreaking enchantment dosent apply when flying, consuming the normal 1 durability per second when flying instead of calculating the chance for not using the durability.

### BetterEnd

2.0.4

### BCLib

2.0.7

### Fabric API

0.57.0

### Fabric Loader

0.14.8

### Minecraft

1.19

**Comment by quiqueck** [comment]
Thanks for reporting. While I do not think that the latest updates changed anything specific to elytra, could you please tray again with our latest updates?

**Comment by HallowedPaladin** [comment]
Tried in version 2.0.9, same result.

**Comment by quiqueck** [comment]
Hm, I can't seem to reproduce this. Tested with the Armoured and Crystalite Elytra on the ChestPlate Slot.

Do you have other mods installed?

**Comment by ambientNexus** [comment]
Experiencing this issue as well, version 2.1.6 of Better End. Tested both for cape trinket slot and chestplate slot, issue persisted across both.
