### ISSUE TITLE
[Bug] End Stone Smelter not available

### ISSUE THREAD

**Issue by hanloon** [quiqueck/BetterEnd#46]
### What happened?

I've gotten it down but I can't use it or even get into its interface

### BetterEnd

2.0.2

### BCLib

2.0.5

### Fabric API

0.57.0+1.19

### Fabric Loader

0.14.8

### Minecraft

1.19

**Comment by hanloon** [comment]
I'm using aternos server so don't know if this will make a difference

**Comment by quiqueck** [comment]
Could you please upgrade to the latest versions of BCLib (2.0.16)  and BetterEnd (2.0.9)?

**Comment by hanloon** [comment]
Thank you for your fast processing, this problem has been solved

**Comment by hanloon** [comment]
Man another problem now I don't even know what's going on the game crashes here's the server report for aternos https://mclo.gs/WaedwVw (mods same as client)

**Comment by hanloon** [comment]
sorry i don't speak english

**Comment by hanloon** [comment]
Sorry for the wrong link I uploaded above, please use this link
https://mclo.gs/vVjC9sH

**Comment by quiqueck** [comment]
You need to update BetterNether as well
