### ISSUE TITLE
[Bug] the infusion pedestal doesn't open

### ISSUE THREAD

**Issue by T-A-D-M-19** [quiqueck/BetterEnd#462]
### What happened?

the infusion pedestal doesn't open and the end stone smelter doesn't open ether.

### BetterEnd

4.30

### BCLib

3.30

### Fabric API

0.9

### Fabric Loader

0.15

### Minecraft

1.20.1

**Comment by OpenBagTwo** [comment]
This is on 1.20.1?

**Comment by T-A-D-M-19** [comment]
yes

**Comment by OpenBagTwo** [comment]
Can you edit your first post to include the other mods you're using (and their versions)?

**Comment by T-A-D-M-19** [comment]
nvm its fixd somehow

**Comment by OpenBagTwo** [comment]
@T-A-D-M-19 glad to hear. Can you close this issue then?
