### ISSUE TITLE
[Bug] always crash when creating normal world

### ISSUE THREAD

**Issue by Hugs288** [quiqueck/BetterEnd#464]
### What happened?

when creating a vanilla (not better x) world, always crash. both in single player and dedicated server.
with only betternether everything works fine.
[crash-2024-08-24_13.52.57-server.txt](https://github.com/user-attachments/files/16736242/crash-2024-08-24_13.52.57-server.txt)

### BetterEnd

21.0.9

### BCLib

21.0.13

### Fabric API

0.102.0+1.21

### Fabric Loader

16.2

### Minecraft

1.21

**Comment by OpenBagTwo** [comment]
This issue has already been reported in #448, and a fix has been proposed in #450, so I would ask that you close this and follow the other issue instead.

If you'd like to try out the fix, I have an experimental (not supported) build [here](https://github.com/OpenBagTwo/BetterEnd/releases/tag/21.0.10%2Bopenbagtwo.240813). But bear in mind—I am not the developer of BetterEnd.
