### ISSUE TITLE
[Suggestion] Compatibility with "Every Compat"

### ISSUE THREAD

**Issue by szunakabeats** [quiqueck/BetterEnd#48]
### Description

This Mod serves as an addon to many popular mods and is meant to fill in the gaps by adding all the blocks that such mods add in all wood types currently installed. It does not just add some, every block type added is available in ALL wood types.

so i noticed that "every compat" is not working with betterend and betternether and so i opened a [issue](https://www.curseforge.com/minecraft/mc-mods/every-compat/issues/14) on MehVahdJukaar's side.

This is what it looks like now: https://imgur.com/a/8jBrJWq

I don't know on which side the problem lies and that's not my point. but it would be really nice if you could make furniture from '[Another Furniture](https://www.curseforge.com/minecraft/mc-mods/another-furniture)' with the wood from BetterNether and BetterEnd

**Comment by quiqueck** [comment]
Hi, and thanks for reporting.

From the looks of it, this is not an issue on our side. If however it turns out that the every compat devs need some changes from us I'll be happy to add them :)

Just re-open this issue...

**Comment by szunakabeats** [comment]
i'll let them know :) thx !
