### ISSUE TITLE
[Question/Bug?] Is this mob being this overpowered an intended feature?

### ISSUE THREAD

**Issue by NikoboiNFTB** [quiqueck/BetterEnd#481]
### What happened?

Clip of what happened: 
https://github.com/user-attachments/assets/3301ae05-fdfb-4a8a-bc73-af3587a9ee02
(TL;DR I got one tapped by a random mob) 

This feels very overpowered and out of place. I was wearing full protection 4 Fireruby armor, and I had 16 hearts and this mob still one tapped me, so I'm left wondering if it's an intended feature or if I died to a bug?

It appears as if the mob spawned from the spawner I broke, which seems kinda peculiar for a mob that one hits you. A boss enemy or a trial spawner would make more sense. 

Expected outcome would be taking a maximum of maybe 4 hearts, and that's already a lot. For reference, a Vindicator takes less than 1 heart with my gear.

(Minecraft game version is 1.21, but it's not available in the box below)

### BetterEnd

21.0.11

### BCLib

21.0.13

### Fabric API

0.102.0

### Fabric Loader

0.16.5

### Minecraft

1.20.4

**Comment by liangmoe** [comment]
betterend does not add such weird mob

**Comment by NikoboiNFTB** [comment]
> betterend does not add such weird mob

Oh thank you! Do you know if the structure is from BetterEnd? It's probably hard to tell where I am in the video, but I'm gonna go try to find it in game right now. Maybe I'll find some clues as to what mod adds it. 

I suspect it might be a When Dungeons Arise structure, but the mobs in those are not that OP either. 

I'll get back to this if I find one.

**Comment by liangmoe** [comment]
install this https://modrinth.com/mod/wits and try type `/wits` while near the structure, the helpful message should showed to you

**Comment by NikoboiNFTB** [comment]
> install this https://modrinth.com/mod/wits and try type `/wits` while near the structure, the helpful message should showed to you

That sounds incredibly useful. Thank you!

**Comment by NikoboiNFTB** [comment]
I have confirmed it is an "Aviary" from "When Dungeons Arise," I'll have to check with them.
