### ISSUE TITLE
[Bug] See through blocks at Ylevel 64

### ISSUE THREAD

**Issue by BobminiJr** [quiqueck/BetterEnd#490]
### What happened?

When I load up a world while using the better end mod with these mods this happens. The mod conflict is between betterend and Sodium. When I was able to remove either one the problem went away but I need sodium for the other mods and optimization. 
![image_2024-10-16_130901504](https://github.com/user-attachments/assets/8949851c-90d9-4b6e-a3e9-cb0ba1540b56)
![image](https://github.com/user-attachments/assets/a328a41e-daf8-4182-ad17-427577bb26cd)

### BetterEnd

4.0.11

### BCLib

3.0.14

### Fabric API

0.86.1

### Fabric Loader

0.16.7

### Minecraft

1.20.0

### Other Mods

```shell
Check photo from main post for the mod list.
```

**Comment by liangmoe** [comment]
Your sodium is outdated

**Comment by BobminiJr** [comment]
> Your sodium is outdated

When I look on Modrinth.com and filter for version 1.20 it only gives one version. Do u know where I can find the up to date version of sodium that is outdated?

**Comment by BobminiJr** [comment]
Fixed it by going a version down of betterend. Going from 4.0.11 to 4.0.10 fixed the issue.
