### ISSUE TITLE
[Suggestion] EMI support

### ISSUE THREAD

**Issue by Pirogiran** [quiqueck/BetterEnd#51]
### Description

EMI supports Crafting tree and some other features that REI don't support. So, can you add support for EMI on 1.18.2 if it's not too difficult? 
And thanks for quality content!

**Comment by quiqueck** [comment]
Hi, and thanks for your suggestion. Since 1.18.2 will not receive any new content, I'll add is as an Enhancement for 1.19 and up.

**Comment by Pirogiran** [comment]
Thanks!

**Comment by quiqueck** [comment]
Available in 2.0.11
