### ISSUE TITLE
[Bug]: Bookshelfs dont enhance the Enchanting Table

### ISSUE THREAD

**Issue by xanthian** [quiqueck/BetterEnd#54]
### What happened?

As title.

Put appropriate amount of bookshelves around the enchanting table, no level 30 enchant available.
Repeat process with vanilla bookshelf, level 30 enchant shown

(no hidden agenda this time)

### BetterEnd

1.1.1

### BCLib

1.4.7

### Fabric API

0.58.0

### Fabric Loader

0.14.8

### Minecraft

1.18.2

### Relevant log output

```shell
na
```

### Other Mods

```shell
na
```

**Comment by quiqueck** [comment]
Fixed in the 1.19 releases.
