### ISSUE TITLE
[Suggestion] No mossy dragon bone block is generated & Renewable smaragdant crystal

### ISSUE THREAD

**Issue by FalseJ** [quiqueck/BetterEnd#56]
### Description

Our server is 1.18.1 so we're using the BetterEnd.1.0.1 (didn't test it in 1.0.3 though). 
1. While exploring the world, I've noticed there's no "Mossy dragon bone" block is generated in dragon grave biome. I notice that you can transform dragon bone block into mossy dragon bone using bone meal, but I need a first "mossy dragon bone" to do so...

2. the smaragdant crystals are wonderful building material! (Luminous slabs and stairs!) However, it turns out those crystals are not renewable? I add a recipe in our server to make smaragdant crystal can be crafted from 2 crystals and 2 emeralds to solve the problem, but it's kind of lame.. Can you make them grow like amythyst? or regenerated like antient emerald ice? It's just so strange that smaragdant crystal are un-renewable but can be crafted into stone tools

I played this mod for a really long time and really enjoying it! hope these suggestions can help it getting better "Better End"!

**Comment by ChristopherJ123** [comment]
An idea of farming smaragdant crystal would be adding a Budding smaragdant crstal block which works like Budding amethyst block in 1.19, crystals would grow on every side of the block overtime.

Maybe they would spawn hidden inside covered by normal smaragdant crystals blocks
