### ISSUE TITLE
[Suggestion] Any support for Bluemap?

### ISSUE THREAD

**Issue by LemonPAKA** [quiqueck/BetterEnd#57]
### Description
https://bluemap.bluecolored.de/
![QQ截图20220804090309](https://user-images.githubusercontent.com/17202894/182847419-51283e32-f4d2-4e58-85b0-a8ad68f9d60e.png)
![QQ截图20220804090223](https://user-images.githubusercontent.com/17202894/182847433-7b0d9a6d-96fe-4686-b87a-95290553003a.png)

**Comment by quiqueck** [comment]
We currently do not have the resources to do support for external tools. Sorry :(

But we are of course happy to accept any PRs :)
