### ISSUE TITLE
Exit portal not spawn on mc 1.19

### ISSUE THREAD

**Issue by wielh** [quiqueck/BetterEnd#6]
### What happened?

Exit portal not spawn when we enter the end first time

### BetterEnd

2.0.0

### BCLib

2.0.1

### Fabric API

0.55.2

### Fabric Loader

0.14.7

### Minecraft

1.19

**Comment by quiqueck** [comment]
Hi, and thanks for contacting us. Do you mean the portal that spawns after the dragon fight?

**Comment by wielh** [comment]
Yes. It can spawn after I edit lfile level.dat. Thanks
