### ISSUE TITLE
Eternel protal not working property[Bug] 

### ISSUE THREAD

**Issue by wielh** [quiqueck/BetterEnd#60]
### What happened?

Some eternel protals not generated in overworld, and we sometimes can go through form overworld to the end but  cannot  form the end to overworld by some other eternel protals.

### BetterEnd

2.0.10

### BCLib

2.018

### Fabric API

0.58.0

### Fabric Loader

0.14.9

### Minecraft

1.19

### Relevant log output

```shell
none
```

**Comment by quiqueck** [comment]
I think I found a fix, however it will only work for newly activated portals.

**Comment by quiqueck** [comment]
The fix was just released for 1.19.3 and will be released for older 1.19 Versions with the next update
