### ISSUE TITLE
[Bug] Can't craft end dust

### ISSUE THREAD

**Issue by OpenBagTwo** [quiqueck/BetterEnd#64]
### What happened?

In Minecraft 1.19.2, no matter which anvil I try or hammer I use, I cannot craft end dust from either ender shards or ender pearls. I've tried this in brand new worlds and in a fresh MultiMC instance with no other mods enabled (except the Fabric API).

Downgrading to Minecraft 1.19 and BetterEnd 2.0.11 / BCLib 2.0.20, I am able to get end shards, but only:
- in a thallasium anvil (not an iron one)
- By putting the shards / pearls in the first slot and the hammer in the second, which is the opposite orientation of the image in the wiki:
    ![hammer on the left](https://static.wikia.nocookie.net/better-end-mod/images/4/4a/How_To_craft_End_Dust.png/revision/latest/scale-to-width-down/345?cb=20210605032656)

[1] Note the newest version isn't available in the dropdown

### BetterEnd

2.1.0

### BCLib

2.1.0

### Fabric API

0.60.0

### Fabric Loader

0.14.9

### Minecraft

1.19.2

### Other Mods

I've tried this in a completely fresh instance with no other mods loaded except the newest Fabric API.

**Comment by TwoFacedNecromancer** [comment]
Also having the same issue. Also cant cant craft forged plates.

**Comment by EL3ST** [comment]
Having the same issue, no recipes involving new anvils or hammers seem to work.

**Comment by jdawg3636** [comment]
Same issue - present in the Better Minecraft [Fabric] 1.19.2 v5 https://www.curseforge.com/minecraft/modpacks/better-mc-fabric/files/3988024

**Comment by TuxedoKamen29** [comment]
Same issue Here. 1.19.2 Fabric. Modpack was downloaded via CurseForge. It's not working in multiplayer nor in Singleplayers.
Version Better MC [FABRIC] 1.19.2 v6 - (Beta).

**Comment by quiqueck** [comment]
Fixed with BCLib 2.1.1.

**Comment by cufufy** [comment]
Broken in 1.21.1 2026
