### ISSUE TITLE
All Anvil Crafting Recipes are broken [Bug] 

### ISSUE THREAD

**Issue by diamonddevv** [quiqueck/BetterEnd#66]
### What happened?

Every single anvil crafted recipe is impossible.

### BetterEnd

2.1.0

### BCLib

2.1.0

### Fabric API

0.60.0

### Fabric Loader

0.14.9

### Minecraft

1.19.2

### Other Mods

```shell
Apple Skin
Bad Packets
Better Nether
DiaLabs
EMI
Enderism
Fabric API
Ferrite Core
Lambdynamiclights
lazydfu
lithium
modmenu
Mouse Tweaks
Sharp Tone
Sodium
Starlight
WTHIT
```

**Comment by ghost** [comment]
I can confirm this issue for the same version, without additional mods.

**Comment by quiqueck** [comment]
Duplicate of #64
