### ISSUE TITLE
Actually Enabling Flower Pots? [Suggestion/Correction] 

### ISSUE THREAD

**Issue by ajaelle12** [quiqueck/BetterEnd#69]
### Description

Its mentioned in the wiki and description that the flower pots should be able to hold a variety of plants. It doesn't seem to actually be implemented though? This has been missing from 1.17 in forge and fabric versions till now- in my experience. It would be awesome of it was functional for builds! tyvm for your time.

**Comment by themasterswordmaster** [comment]
yea right now theyre more decorative vases than actual flower pots, would be nice to... actually be able to put plants in them

**Comment by FalseJ** [comment]
Actually, it can hold most of the plants in BetterEnd mod (but not vanilla minecraft flowers though...).
All you need to do is put the correlated "end moss" into the pots, and then put the plants on it. For example you can right click flower pot with "crystal moss block" then right click  with "crystal grass"

oh... but I never test it in 1.17 though, we're using the 1.18.1 ver

**Comment by paulevsGitch** [comment]
All ports works fine in 1.17 version
