### ISSUE TITLE
Aeternium Anvil durability is questionably low

### ISSUE THREAD

**Issue by StevenC21** [quiqueck/BetterEnd#74]
### What happened?

The Aeternium Anvil invariably breaks after exactly 3 uses when enchanting items.

Tested with an Aeternium Sword and a book of Sharpness 5, Unbreaking 3, Mending, enchanted in that order.

I enchanted it in the Overworld.

Note: I am actually on 1.19.2, but that is not currently an option for the Minecraft Version at the time of making this bug report.
### BetterEnd

2.1.0

### BCLib

2.1.0

### Fabric API

.60.0

### Fabric Loader

0.14.9

### Minecraft

1.19.1

**Comment by quiqueck** [comment]
Changed in BetterEnd 2.1.1

**Comment by grundyboy34** [comment]
fc8e860 did not fix this. Instead, the same line from that commit needs a change to the if statement's logic.
See https://github.com/quiqueck/BCLib/commit/fc8e8603693ed5bb34a5bd14e2e88e9fe6b1eb14#r108405421
