### ISSUE TITLE
[Bug] Megalakes are overpopulated with end lotus flowers

### ISSUE THREAD

**Issue by user433453** [quiqueck/BetterEnd#76]
### What happened?

it just naturally happens.

### BetterEnd

2.1.0

### BCLib

2.1.0

### Fabric API

0.58.0

### Minecraft

1.19

**Comment by SuperiorDonut** [comment]
Same issue here, with the only difference being I'm on Fabric API 0.61.0 and Minecraft version 1.19.2; Attached is an image showing what this looks like.
![unknown](https://user-images.githubusercontent.com/114554928/192688498-3937e74e-2c4a-4c92-af99-5882bb18c615.png)

**Comment by ChristopherJ123** [comment]
I think it's supposed to be like that? Not sure though.

**Comment by quiqueck** [comment]
Changed in BetterEnd 2.1.1
