### ISSUE TITLE
[Bug] Eternal portal isn't spawning

### ISSUE THREAD

**Issue by Eatham532** [quiqueck/BetterEnd#8]
### What happened?

I used /located but the command didn't send me to an eternal portal. Restarted my server and tried again. (From the location that I was told an eternal portal was at before I restarted) and the location was different.

Also, P.S. The github repo link is wrong on the curseforge page. Sends you to the paulevsGitch repo not the quiquek one.

### BetterEnd

2.0.1

### BCLib

2.0.4

### Fabric API

0.55.3

### Fabric Loader

0.14.7

### Minecraft

1.19

### Other Mods

```shell
Nothing else related to the end generation.
```

**Comment by quiqueck** [comment]
Hi and thanks for reporting.

I can not reproduce this with my current build. So either it was fixed since 2.0.1 releases, or there is another incompatibility going on. Could you provide your mod-list anyway?

Also, could you try the command `/locate poi betterend:eternal_portal_inactive` This is a block-level search for portal blocks. Just in case the porta generates somewhere else.

**Comment by Eatham532** [comment]
![image](https://user-images.githubusercontent.com/78714349/173689700-b6c455b8-3a5a-4187-990b-e87fd1f33eb4.png)
This is my mod list. Wait a sec while I try again on my server and client.

**Comment by Eatham532** [comment]
Used /locate structure betterend:eternal_portal and that didn't work.

and when doing locate poi I get this:
![2022-06-15_07 17 05](https://user-images.githubusercontent.com/78714349/173690583-3f4545ed-8963-4d48-a074-8ef95eb6aa87.png)

**Comment by Eatham532** [comment]
Just checked client side and that didn't work either. So it could be mod incompatibilities
Here is my log if that helps.

[latest.log](https://github.com/quiqueck/BetterEnd/files/8904031/latest.log)
.

**Comment by quiqueck** [comment]
Thanks for the update. BiomeMakeover sounds like something that could potentially alter structure placement. I'll test with that.

**Comment by Eatham532** [comment]
Really? It only does overworld generation though. Thats weird.

**Comment by quiqueck** [comment]
Oh, I might have worded that wrong. Basically I am not sure why the portals do not spawn in your world. And (just by name) the mod that would be my first candidat to check would be  BiomeMakeover, as it (at least) has something to do with biome generation :)

I also did think about two other things: Do you maybe have a level seed for me? Mabye it is specific to a certain seed. And is this a fresh world from 1.19 or was it converted from a previous Minecraft.

Sorry for asking so many question, but I currently have no clue as to why they are not spawning in your world. :(

**Comment by Eatham532** [comment]
I did two fresh seeds. And there were none in both. Each on a seperate computer. I can try to find out which one is the incompatible. It could also be one of my optimisation mods...

**Comment by Eatham532** [comment]
Or it could be collective...

**Comment by Eatham532** [comment]
Nope nevermind. Just tried betterend by itself and it didnt work. Better end 2.0.2, bclib 2.0.5 and fabric api 0.56.0 1.19

**Comment by Eatham532** [comment]
Also... Another thing. For some reason every time I go into the end with better end I am like 50 blocks away from the main island.

**Comment by Eatham532** [comment]
Did you find the bug?

**Comment by DragonWoven** [comment]
having the same issue on 1.19

**Comment by quiqueck** [comment]
Unfortunately no. So far I was unable to reproduce it. The Portals spawn just fine in my worlds...
Does your instance have some configs around for BClib/BN? If so, could you maybe remove them and let the mods regenerate.

**Comment by quiqueck** [comment]
Could either of you maybe start a new World and immediately leave it. Then back it up and attach the backup as well as the corresponding log file here. Maybe that will help me to reproduce the issue

**Comment by Eatham532** [comment]
Ok, I will do it tomorrow. (Its night right now for me.)

**Comment by Eatham532** [comment]
Ok, I will do it tomorrow. (Its night right now for me.)

**Comment by DragonWoven** [comment]
I found my problem, they don't spawn when better nether is installed

**Comment by Eatham532** [comment]
Are you saying if you have better nether it fixes it?

**Comment by DragonWoven** [comment]
no, when I have better nether installed, it won't spawn

**Comment by Eatham532** [comment]
Have you tried it without better nether? I dont use better nether and it wont spawn.

**Comment by Eatham532** [comment]
Ok, the eternal portal generated this time. But is this ment to happen? I think the eternal portal is generating weird and that's why I couldn't find it. (FYI the portal platform is hanging off the edge with no support)

![2022-06-25_13 39 05](https://user-images.githubusercontent.com/78714349/175756844-133604c0-9608-4783-b759-e6dda1b34c83.png)


Also the obsidian platform still was 50+ blocks away. 
![2022-06-25_13 41 20](https://user-images.githubusercontent.com/78714349/175756863-7cd5840e-aa44-4040-a6a5-60868db988dc.png)


**World**
[BetterEnd Eternal Portal Test.zip](https://github.com/quiqueck/BetterEnd/files/8983805/BetterEnd.Eternal.Portal.Test.zip)

**Log**
[latest.log](https://github.com/quiqueck/BetterEnd/files/8983806/latest.log)

**Comment by quiqueck** [comment]
Thanks for the files. I Just tested alongside BetterNether, and the portal did generate just fine.
I Uses the world you sent me, did reset the End and found a new portal here:
<img width="966" alt="image" src="https://user-images.githubusercontent.com/280847/175833435-f3163df1-e1ad-4b47-b928-6b99493192cc.png">

Could you please check those coordinates?

**Comment by Eatham532** [comment]
Sure, That is very weird. I never saw that biome will try again.

**Comment by Eatham532** [comment]
**The same place but with coords**


![2022-06-27_07 10 44](https://user-images.githubusercontent.com/78714349/175834030-ec01f186-4059-44a8-b224-dacab2a9b1d9.png)



**The exact coords shown in your image**
*The eternal portal was further underneath. Shown in the seccond image*


![2022-06-27_07 11 57](https://user-images.githubusercontent.com/78714349/175834044-291165bf-6164-40fb-9f71-bbc3cbc614b4.png)

![2022-06-27_07 16 38](https://user-images.githubusercontent.com/78714349/175834126-832e6d0f-a0c7-4207-8a62-59207a40d31b.png)


**Mods used**
 
![image](https://user-images.githubusercontent.com/78714349/175834173-8d333185-4935-44b6-b7c8-9b0c9cff08f2.png)

**Comment by quiqueck** [comment]
I just release 2.0.3 (the version I have been testing with). Could you please revisit those locations with the latest versions?

**Comment by Eatham532** [comment]
sure

**Comment by Eatham532** [comment]
![2022-06-30_17 59 34](https://user-images.githubusercontent.com/78714349/176624771-1ccf0946-2999-4198-89ff-ac28af6eff9f.png)
Yep! Perfect generation. There is one flower the didn't generate. Not a big deal though. My portal is broken and yours is not. Unless you put that block there.

The other eternal portal i found generated a lot higher than normal and was in a different biome. It also was not inside endstone either. Good Job!

**Comment by quiqueck** [comment]
Thank You for the patience and help. :)
