### ISSUE TITLE
Missing Flying Lantern Feature in Lantern Woods biome [Bug] 

### ISSUE THREAD

**Issue by ChristopherJ123** [quiqueck/BetterEnd#86]
### What happened?

Flying Lanterns doesn't generate in latest version of Better End (picture).

![2022-10-05_02 44 44](https://user-images.githubusercontent.com/86960084/193917239-f4c9c362-00fe-49ca-aac3-b62e445007e7.png)
![2022-10-05_02 44 38](https://user-images.githubusercontent.com/86960084/193917274-225d1dd2-6e44-49af-a68a-be5fb79fdbd8.png)

### BetterEnd

2.1.0

### BCLib

2.1.0

### Fabric API

0.62.0

### Fabric Loader

0.14.9

### Minecraft

1.19.1

**Comment by quiqueck** [comment]
Fixed in BetterEnd 2.1.1
