### ISSUE TITLE
[Bug] Incompatible with C2ME Threaded feature placement (1.19.2)

### ISSUE THREAD

**Issue by TheUserCreated** [quiqueck/BetterEnd#87]
### What happened?

While pre-generating chunks on a fabric server using chunky, C2ME, and BetterEnd, there is a somewhat rare bug seemingly involving feature placement (C2ME has a by default enabled threaded feature placement option)

Steps to reproduce are to have at least those three mods installed and generate chunks using chunky until the issue arises, usually manifesting as a crash. If you do test this, be sure to enter the end at least once before starting chunky. 
I did talk to the developer of C2ME but was told the bug report should be filed here too. Below are the crash logs and server log. You may notice many more mods, but I was able to reproduce with just the three mentioned above on my local machine.
[latest.log](https://github.com/quiqueck/BetterEnd/files/9711962/latest.log)
[crash-2022-10-04_12.09.26-server.txt](https://github.com/quiqueck/BetterEnd/files/9711963/crash-2022-10-04_12.09.26-server.txt)

### BetterEnd

2.1.0

### BCLib

2.1.0

### Fabric API

0.61.0

### Fabric Loader

0.14.9

### Minecraft

1.19.1

**Comment by quiqueck** [comment]
Yes, BetterEnd does not support Threaded Feature Processing
