### ISSUE TITLE
Betterend stones should be able to be placed on stone cutter [Feature] 

### ISSUE THREAD

**Issue by ChristopherJ123** [quiqueck/BetterEnd#89]
### What happened?

Just like how stones in vanilla can be used on stone cutter, so does Betterend's! Currently all betterend stones that have variants is: Flavolite, violecite, sulphuric rock, Jadestones, smaragdant crystal, thallasium, terminite.

### BetterEnd

2.1.0

### BCLib

2.1.0

### Fabric API

0.62.0

### Fabric Loader

0.14.9

### Minecraft

1.19.1

**Comment by ChristopherJ123** [comment]
I made a full datapack for this 😀 you can use it

[BE Stonecutter recipes datapack 1.19+.zip](https://github.com/quiqueck/BetterEnd/files/9727996/BE.Stonecutter.recipes.datapack.1.19%2B.zip)

**Comment by quiqueck** [comment]
Added in BetterEnd 2.1.1
