### ISSUE TITLE
[1.18.2 and 1.19] Properly tag betterend's biomes as end with biome tag

### ISSUE THREAD

**Issue by TelepathicGrunt** [quiqueck/BetterEnd#9]
### What happened?

Continuing from this PR: https://github.com/paulevsGitch/BetterEnd/pull/483

Since the introduction of biome tags in 1.18.2, biome mods should tag their biomes with proper biome tags. In 1.18.2, BetterEnd's biomes should be in the c:is_in_end biome tag. In 1.19, use the minecraft:is_end biome tag (introduced in 1.19). This will maximize compatibility with other mods that are now using biome tags.

Paul mentioned that the tags in Better X mods do not use json for tags so I cannot move my PR over to here as it won't be accepted it seems.

### BetterEnd

2.0.2

### BCLib

2.0.5

### Minecraft

1.18.2

**Comment by quiqueck** [comment]
Same as with BetterNether, in 1.19 the Biomes should be added to the tag. How did you notice that they are missing?

**Comment by quiqueck** [comment]
<img width="966" alt="image" src="https://user-images.githubusercontent.com/280847/176621315-69f484e1-a890-4f2b-8d92-a74e0e4531d7.png">
As far as I can see the structures appear to be added fine now (tested with BetterEnd 2.0.3). Please let me know if there are still issues.
